spring.application.name=gateway

server.port=${GATEWAY_PORT:8085}

# Frequency of heartbeats sent by the client to the server
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.prefer-ip-address=true
# Frequency of registry data retrieval from the server to the client's local cache
eureka.client.registry-fetch-interval-seconds=5
# Eureka Service Url
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

spring.cloud.gateway.server.webflux.routes[0].id=${SONG_SERVICE_NAME:song-service}
spring.cloud.gateway.server.webflux.routes[0].uri=lb://${SONG_SERVICE_NAME:song-service}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/songs/**

spring.cloud.gateway.server.webflux.routes[1].id=${RESOURCE_SERVICE_NAME:resource-service}
spring.cloud.gateway.server.webflux.routes[1].uri=lb://${RESOURCE_SERVICE_NAME:resource-service}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/resources/**
