spring.application.name=${EUREKA_SERVICE_NAME:eureka-service}

server.port=${EUREKA_SERVICE_PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
